# Generated by Django 6.0.5 on 2026-05-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones_barberia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barberos/'),
        ),
    ]
